#!/bin/bash
ACTION=$1

PYTHON_PKG_PATH="$(python -c 'import sys; print(sys.path[-1])')/season"
WIZ_GIT_PATH=$(pwd)
WIZ_LIB_PATH="$WIZ_GIT_PATH/src/season"

if grep -Fq "github.com/season-framework/wiz" .git/config
then
    case $ACTION in
        init)
            # install git source as python package
            rm $PYTHON_PKG_PATH
            ln -s $WIZ_LIB_PATH $PYTHON_PKG_PATH 

            # create dev project
            rm -rf "$WIZ_GIT_PATH/dev"
            wiz create dev
            ;;

        dump)
            # ide dump
            rm -rf src/season/data/ide/*
            cp -r dev/ide/angular src/season/data/ide/angular
            cp -r dev/ide/assets src/season/data/ide/assets
            cp -r dev/ide/package.json src/season/data/ide/package.json

            # plugin dump
            rm -rf src/season/data/plugin/*
            cp -r dev/plugin/* src/season/data/plugin/
            find src/season/data -name ".git" -type d -exec rm -rf "{}" \; 2> /dev/null
            find src/season/data -name "shortcut.custom.ts" -type f -delete
            find src/season/data -name "shortcut.plugin.ts" -type f -delete
            ;;

        build)
            VERSION=$2
            rm -rf dist
            rm -rf build
            python setup.py bdist_wheel
            twine upload dist/season-$VERSION-py3-none-any.whl --verbose
            ;;

        *)
            echo "wiz-build [ init | dump | build <version> ]"
            ;;
    esac
else
    echo "Not wiz project"
fi
